# Generated by Django 4.2.5 on 2023-09-23 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookingTbale',
            new_name='BookingTable',
        ),
    ]
